### ISSUE TITLE
Crashes when listen config is `false`

### ISSUE THREAD

**Issue by runeb** [sanity-io/groq-store#13]
Repro

```javascript
const { groqStore } = require('@sanity/groq-store')

const store = groqStore({
    projectId: '27lgnhnz',
    dataset: 'workflow',
    listen: false, // true does not produce error
    overlayDrafts: true
})

const run = async () => {
    const docs = await store.query(`*[].title`)
    console.log(docs)
    store.close()
}

run()
```

Running the above
```
➜  repro npm ls
test@1.0.0 /Users/runeb/tmp/repro
└── @sanity/groq-store@0.4.1
➜  repro node -v
v16.13.1
➜  repro node query.js
/Users/runeb/tmp/repro/node_modules/@sanity/groq-store/dist/node/groq-store.js:219
    stagedDocs = undefined;
               ^

ReferenceError: Cannot access 'stagedDocs' before initialization
    at onUpdate (/Users/runeb/tmp/repro/node_modules/@sanity/groq-store/dist/node/groq-store.js:219:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async loadDataset (/Users/runeb/tmp/repro/node_modules/@sanity/groq-store/dist/node/groq-store.js:333:5)
    at async Object.query (/Users/runeb/tmp/repro/node_modules/@sanity/groq-store/dist/node/groq-store.js:337:5)
    at async run (/Users/runeb/tmp/repro/query.js:11:18)
```

changing the `listen` config to `true` avoid the error

**Comment by runeb** [comment]
Moving these up to line 19 apparently fixes this issue, but there may be some program flow errors or wrong assumptions with update handling here, so I'll leave this without a PR

https://github.com/sanity-io/groq-store/blob/main/src/syncingDataset.ts#L47-L49

**Comment by stipsan** [comment]
@runeb I've moved these to fix other issues that moving to [vitest](https://github.com/sanity-io/groq-store/pull/78) picked up. We can probably close this?

**Comment by runeb** [comment]
Thanks @stipsan
